feat: Allow to store Output in context.Context
mesosphere/dkp-cli-runtime pull request #44
Opened 2022-03-18 13:50 UTC by mikolajb

We often pass context together with Output type, e.g.:
- https://github.com/mesosphere/kommander-cli/blob/406ee4c4f8fd676695087248b5b91423750a583a/pkg/git/gitea/portforward.go#L17
- https://github.com/mesosphere/kommander-cli/blob/4b423c03e5f65322e23ada8d2a3ee61355e27016/pkg/charts/upload.go#L24
- https://github.com/mesosphere/kommander-cli/blob/12c908f985b24576e7f15cf4fb2f146742caefb1/pkg/helm/helm.go#L74

I would like to allow to store `Output` in `Context` so we can only pass one parameter and worry about `Output` only when root `Context` is created.

2022-03-18 13:53 UTC, mhrabovcin requested changes
I'd rather not do this. This hides output as a dependency in context and makes the code less readable and explicit.

2022-03-18 15:13 UTC, floridoo commented
I tend to agree with Martin on this. It makes it invisible to the caller of a function that the `Context` needs to have an `Output` set.
I used this pattern in some other project and more than once we ran into runtime errors (impossible to detect on compile time) because someone passed a `context.Background()` instead.

If we want to have it, I would prefer to use make it explicit using an interface:
```go
type ContextWithOutput interface {
	context.Context
	Output() output.Output
}
```
Quick example:
https://goplay.tools/snippet/zJy57YdQue0

2022-03-22 22:12 UTC, mikolajb commented
@mhrabovcin, @floridoo thanks for a quick response and constructive feedback 🙌🏻!

@mhrabovcin For me, logging is part of the initialization, bootsrapping, etc. I think it should be as invisible and effortless as possible so a developer can focus on important things. With this approach, the logger would be initialized once where the root context is created and that would be end of it. I don't see any problems with that approach. Why do you think it is better to pass logger explicitly?

@floridoo the solution I proposed won't cause runtime errors since there is a default value: it always returns a valid logger. Correctly if I'm wrong, but if we introduce a new type (e.g., `ContextWithOutput`), it won't go through third-party libraries, right? (A case when context is passed from _our_code_ ➡️ _library_ ➡️ _our_code_). At lest not in the easy way. I guess this is one of the reasons that `context.Context` can hold any value.

This is another example why I think we could benefit from less explicit approach: https://github.com/mesosphere/kommander-cli/search?q=NewNonInteractiveShell&type=code (locally I count 46 occurrences).

2022-03-22 22:25 UTC, floridoo commented
> Correctly if I'm wrong, but if we introduce a new type (e.g., ContextWithOutput), it won't go through third-party libraries, right?
Both `ContextWithOutput` and `context.Context` are interfaces, so that would still work. I updated the Go Playground link above to include a sample like this

2022-03-22 23:12 UTC, mikolajb commented
> Both `ContextWithOutput` and `context.Context` are interfaces, so that would still work. I updated the Go Playground link above to include a sample like this

I meant something like this: https://goplay.tools/snippet/Yi7MDl1DEqa (function `Run3`)

It would also mean that we need to change every `context.Context` to `ContextWithOutput` or do casting every time we want to change it 🤔

2022-03-23 12:03 UTC, floridoo commented
> It would also mean that we need to change every `context.Context` to `ContextWithOutput`

only for those Contexts that you expect to contain an Output. That's the goal: guaranteeing at compile time which Context contains an Output, so you don't need to check at runtime or potentially end up with swallowing output by accident.

Your `Run3` example should look more like this:
https://goplay.tools/snippet/RFIFDoZ7C6w

2022-03-23 12:51 UTC, mhrabovcin commented
> For me, logging is part of the initialization, bootsrapping, etc. 

@mikolajb we're using `Output` library primarily for the CLI output. Although the `Output` interface looks like a logging library it is rather a UI printer and there may be a different expectation on how to process the output. 

My developer view is that, if you're depending on the `Output` there is no advantage of hiding the dependency in the context. I don't see why calling a helper function that would get the `Output` from a context would be "better" than having an explicit dependency in the function args list.

> I think it should be as invisible and effortless as possible so a developer can focus on important things.

As a developer, you don't have to configure anything in the scope of the function. The output library is configured during the app initialization once. I personally think that communicating output back to the user is a very important part of a function. It is the UI that we're building for the end users.

If the `output.NewNonInteractiveShell(io.Discard, io.Discard, 0)` call seems too verbose to you we can create a shortcut that we'd use in our tests.

In general to using `Context` - I don't think we should store in the `Context` any value that is not serializable and couldn't be sent over network connection.

2022-06-14 09:44 UTC, closed without merging